//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.23 at 01:49:06 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sdmx.resources.sdmxml.schemas.v2_0.message;
