//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.23 at 01:49:06 PM CET 
//


package org.sdmx.resources.sdmxml.schemas.v2_0.registry;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConstraintTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConstraintTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Content"/>
 *     &lt;enumeration value="Attachment"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ConstraintTypeType")
@XmlEnum
public enum ConstraintTypeType {


    /**
     * Content constraint.
     * 
     */
    @XmlEnumValue("Content")
    CONTENT("Content"),

    /**
     * Attachment constraint.
     * 
     */
    @XmlEnumValue("Attachment")
    ATTACHMENT("Attachment");
    private final String value;

    ConstraintTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConstraintTypeType fromValue(String v) {
        for (ConstraintTypeType c: ConstraintTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
